### ISSUE TITLE
作業ログ

### ISSUE THREAD

**Issue by miurabo** [miurabo/hiroo_laravel#1]
vue.js について調べてみる

**Comment by miurabo** [comment]
適当にやってみたが動かず
https://jp.vuejs.org/v2/guide/installation.html

**Comment by miurabo** [comment]
![2017-11-18 13 49 29](https://user-images.githubusercontent.com/17590374/32976995-52f53b14-cc67-11e7-8230-155e3561de06.jpg)

**Comment by miurabo** [comment]
[Node\.js と npm インストールとアップデート \- Qiita](https://qiita.com/jaxx2104/items/2277cec77850f2d83c7a)

**Comment by miurabo** [comment]
```
❯  vue init webpack-simple my-project                                                                          [13:44:23]
/usr/local/lib/node_modules/vue-cli/bin/vue-init:60
let template = program.args[0]
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

**Comment by miurabo** [comment]
node.js 古いっぽい
[vue cli not create webpack\-simple · Issue \#618 · vuejs/vue\-cli](https://github.com/vuejs/vue-cli/issues/618)

**Comment by miurabo** [comment]
[Node\.jsとnpmをアップデートする方法 – Rriver](http://parashuto.com/rriver/tools/updating-node-js-and-npm)

**Comment by miurabo** [comment]
update したらいけたっぽい
```
❯  vue init webpack-simple my-project                                                                          [13:54:26]

? Project name my-project
? Project description A Vue.js project
? Author miura <miura@mono-style.co.jp>
? License MIT
? Use sass? No

   vue-cli · Generated "my-project".

   To get started:
   
     cd my-project
     npm install
     npm run dev

**Comment by miurabo** [comment]
/dist/ にbuildしてるくさい
```
 ✔ miura   master  ~/Programs/vuejs_lesson/my-project 
❯ npm run dev                                                                                                  [14:09:10]

> my-project@1.0.0 dev /Users/miura/Programs/vuejs_lesson/my-project
> cross-env NODE_ENV=development webpack-dev-server --open --hot

Project is running at http://localhost:8080/
webpack output is served from /dist/
404s will fallback to /index.html

**Comment by miurabo** [comment]
phpstorm の赤い波線 FileWitcher ECMAScript 6 にしたら収まったくさい

**Comment by miurabo** [comment]
phpstorm の vue のインデントを 2 にすすめてくるやつは js のインデントを 2 にしたら収まった

**Comment by miurabo** [comment]
入門している
[Vue\.js入門 \- Qiita](https://qiita.com/yasui05821/items/cbd8d128bc9023c6f3a7)

**Comment by miurabo** [comment]
intelijのプラグインだと思うけど laravel file の作成ボタンが追加されていた。
artisan コマンドの代わりになるかと思ったけど動かず
![2017-11-18 14 25 32](https://user-images.githubusercontent.com/17590374/32977226-68224f40-cc6c-11e7-8ea5-6955490a7aab.jpg)
![2017-11-18 14 25 42](https://user-images.githubusercontent.com/17590374/32977227-69d13982-cc6c-11e7-9f1f-c3bee0cf14c9.jpg)

**Comment by miurabo** [comment]
build したやつ IDE だとうまく動かないので vagrant に httpd 入れて見てみる。docker はまだ使いこなせない

**Comment by miurabo** [comment]
error at vagrant shared folders
```
==> default: Mounting shared folders...
    default: /vagrant => /Users/miura/Programs/vuejs_lesson
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device

**Comment by miurabo** [comment]
[vagrantのshared folderのmountに失敗してしまった場合 \- Qiita](https://qiita.com/ak-ymst/items/bdc37aaf53f857d37fcc)

**Comment by miurabo** [comment]
[Vagrantで共有フォルダのマウントに失敗するときの対処方法 \- Qiita](https://qiita.com/ozawan/items/9751dcfd9bd4c470cd82)

**Comment by miurabo** [comment]
[Vagrant超入門 ~ 5分でcentOSを手に入れよう \- Qiita](https://qiita.com/ritukiii/items/9933e1497237bdac9500)

**Comment by miurabo** [comment]
カーネル更新してみる

**Comment by miurabo** [comment]
押したら消えるやつはimsに流用できそう

**Comment by miurabo** [comment]
エラー解消した。centosのkernelが古くて Guest Additions のインストールに失敗してたぽい

**Comment by miurabo** [comment]
``
[vagrant@localhost ~]$ history
    4  sudo yum install httpd
    6  sudo systemctl start httpd
   12  sudo yum -y update kernel
   13  sudo yum -y install kernel-devel kernel-headers dkms gcc gcc-c++

**Comment by miurabo** [comment]
`npm run build` したやつ vagrant (centos + apache) で動かせた！
![2017-11-18 15 18 53](https://user-images.githubusercontent.com/17590374/32977610-ef1c4f26-cc73-11e7-9441-d682502593ad.jpg)

**Comment by miurabo** [comment]
```
ERROR in ./src/main.js
Module not found: Error: Can't resolve './Post.vue' in '/Users/miura/Programs/vuejs_lesson/my-project/src'
 @ ./src/main.js 10:0-30

**Comment by miurabo** [comment]
Post.vue 追加したが白い

**Comment by miurabo** [comment]
WARN Local package.json exists, but node_modules missing, did you mean to install?
```
❯ npm run dev                                                                                                              [16:04:09]

> @ dev /Users/miura/ims
> npm run development


> @ development /Users/miura/ims
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

sh: cross-env: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

**Comment by miurabo** [comment]
`npm install ` してみる。正解ぽい
```
> npm run dev                                                                                                              [16:06:34]

> @ dev /Users/miura/ims
> npm run development


> @ development /Users/miura/ims
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting                                                                         

 DONE  Compiled successfully in 4100ms                                                                                        16:09:47
                                                                                                                                                                                                                             Asset     Size  Chunks                    Chunk Names
  fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.eot?f4769f9bdb7466be65088239c12046d1  20.1 kB          [emitted]         
fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.woff2?448c34a56d699c29117adc64c43affeb    18 kB          [emitted]         
 fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.woff?fa2772327f55d8198301fdb8bcfc8158  23.4 kB          [emitted]         
  fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.ttf?e18bbf611f2a2e43afc071aa2f4e1512  45.4 kB          [emitted]         
  fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.svg?89889688147bd7575d6327160d64e760   109 kB          [emitted]         
                                                                                               /js/app.js  1.23 MB       0  [emitted]  [big]  /js/app
                                                                                             /css/app.css   147 kB       0  [emitted]         /js/app
 ✔ miura   master±  ~/ims 
❯                                                                                                                          [16:09:47]

**Comment by miurabo** [comment]
`/Users/miura/ims/resources/assets/js/components/Example.vue` に vue ファイル発見

**Comment by miurabo** [comment]
[Laravel 5\.4で Vue\.js開発環境を手軽に作る : アシアルブログ](http://blog.asial.co.jp/1496)

**Comment by miurabo** [comment]
[jQuery で頑張ってしまったことを猛省して Laravel Mix で Vue\.js を勉強した \- atuweb : つながりを作るWebプログラマ](https://atuweb.net/201703_study-laravel-mix-vue/)

**Comment by miurabo** [comment]
[5分でわかるVue\.jsと、jQueryで頑張ってはいけない理由 \| 株式会社インフィニットループ技術ブログ](https://www.infiniteloop.co.jp/blog/2014/06/5min_vuejs/)

**Comment by miurabo** [comment]
#質問 <a href> で post したい場合は action() か url() ヘルパ関数で post ってできるでしょうか？
form 作って js で <a> から蹴る感じしかないですか？

**Comment by miurabo** [comment]
# まとめ
- vue.js についての学習に終始していた
- 調べ物中心になった
- [成果物](https://github.com/miurabo/hiroo_laravel)
- 現状だと進行中の開発案件で POST しまくり jQuery で頑張ってしまいそうなので少しでも取り入れていったほうが良さそう
- VueRouter よくわからなかった
- Laravel で vue.js 使う方法まだわかってない

**Comment by miurabo** [comment]
[jQuery で頑張ってしまったことを猛省して Laravel Mix で Vue\.js を勉強した \- atuweb : つながりを作るWebプログラマ](https://atuweb.net/201703_study-laravel-mix-vue/)

**Comment by miurabo** [comment]
[JavaScriptとCSSスカフォールド 5\.5 Laravel](https://readouble.com/laravel/5.5/ja/frontend)

**Comment by miurabo** [comment]
たべたつさん見てたのこのページかな
[JavaScriptとCSSスカフォールド 5\.5 Laravel](https://readouble.com/laravel/5.5/ja/frontend)
